spring:
  config:
    activate:
      on-profile: local

  docker:
    compose:
      enabled: true
      file: docker/docker-compose.yaml

app:
  greeting:
    message: running in Local

management:
  endpoint:
    env:
      show-values: always
