spring:
  application:
    name: @project.name@

# custom property for banner
app:
  version: @project.version@

management:
  info:
    java:
      enabled: true
    git:
      mode: full
      enabled: true

logging:
  level:
    root: INFO
    org.springframework: INFO