version: '3'

services:
  PostgreSQL16:
    image: 'postgres:16.0'
    ports:
      - '5222:5432'
    environment:
      - 'POSTGRES_DB=boot-graalvm'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=s3cr3t'
    volumes:
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    labels:
      org.springframework.boot.readiness-check.tcp.disable: true
